get http://localhost:3030/
Content-Type: application/json

###

POST  http://localhost:3030/register
Content-Type: application/json

{
    "email": "jonnig6@gmail.com",
    "full_name": "jonathan mwaniki",
    "address": "nyeri",
    "password": "Qwerty123!",
    "Cpassword": "Qwerty123!"
}

###

POST http://localhost:3030/protected
Content-Type: application/json
Authorization: {"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiam9ubmlnNkBnbWFpbC5jb20iLCJmdWxsX25hbWUiOiJqb25hdGhhbiBtd2FuaWtpIiwiYWRkcmVzcyI6Im55ZXJpIiwidXNlcl9yb2xlIjoidXNlciJ9LCJpYXQiOjE2Mzg4MjE0MTcsImV4cCI6MTYzODkwNzgxN30.3yT1Og22LgE2ZnGzuWIqwWC6C2ZVwPi6TTWTfHaz0f8 eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Impvbm5pZzZAZ21haWwuY29tIiwiaWF0IjoxNjM4ODIxNDE3LCJleHAiOjE2Mzk0MjYyMTd9.Zk2ITdLsohV782XiugKXQADHqUGDA6AvtxtP2Arx0V8 "}

###

POST http://localhost:3030/login
Content-Type: application/json

{
    "email": "jonnig6@gmail.com",
    "password": "Qwerty123!"
    
}